User.create!(name: "田中", age: 23)
User.create!(name: "加藤", age: 43)
User.create!(name: "森本", age: 27)
User.create!(name: "山本", age: 56)
User.create!(name: "春日", age: 75)
User.create!(name: "浅田", age: 5)
User.create!(name: "渡辺", age: 52)
User.create!(name: "稲垣", age: 12)